name: temp_rooms
description: Temporary voice channels feature.

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  nyxx: ^4.4.1
  nyxx_interactions: ^4.5.0
  drift: ^2.4.2
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.4.1
