name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoying to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo systemctl stop clasher_bot
            cd clasher_bot/
            git fetch
            git pull
            dart pub get
            sudo systemctl start clasher_bot
